### ISSUE TITLE
add rocketchat TBD.

### ISSUE THREAD

**Issue by 3DJetengine** [MycroftAI/chatter#4]
fourthly,

rocketchat is available as a build [using xubuntu] [candidate](https://forum.snapcraft.io/t/rocket-chat-desktop-snap/222/2) on [forum.snapcraft.io](https://forum.snapcraft.io/t/rocket-chat-desktop-snap/222)

please add rocketchat as an opensource  option [TBD](https://github.com/MycroftAI/chatter#setup).

for best wishes.

**Comment by penrods** [comment]
This is retired
