### ISSUE TITLE
submodule is gone, delete this repo

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/chatter#5]
@btotharye  deleted all his mycroft repos, this one is now useless since it only contains a readme and a submodule pointing to a 404

**Comment by JarbasAl** [comment]
actually, thanks to the wayback machine i could find this fork 

https://github.com/highjinx411/mycroft_proxy

submodule can be updated, or maybe it's better to include those files in this repo withou a submodule to ensure this does not happen again

**Comment by penrods** [comment]
I'm inclined to just ZZZ_ archive this repo.
